import type { Project } from "@/types/project";

/**
 * DEMO / PLACEHOLDER PROJECTS — not real client work.
 *
 * This file is intentionally separate from src/content/projects.ts (the
 * file components actually import). See src/content/README.md for the
 * exact steps to replace this with real work — in short: create
 * src/content/real-projects.ts with the same Project[] shape, then change
 * one import line in projects.ts. No component ever imports this file
 * directly, so nothing downstream needs to change.
 *
 * No real project content exists yet (docs/IMPLEMENTATION_PLAN.md §11
 * item 9: no final project list, no case study copy has been gathered).
 * `coverImage`/`thumbnail` use `kind: "placeholder"`, which renders as an
 * honest labeled frame (see PortfolioMedia/PlaceholderMedia) — never
 * dressed up to look like real finished work.
 */

export const demoProjects: Project[] = [
  {
    id: "northbound",
    title: "Northbound",
    slug: "northbound",
    category: "UI/UX",
    projectType: "Mobile App",
    year: 2025,
    client: "Northbound (early-stage fintech)",
    role: "Product Designer",
    shortDescription: "Cut a 12-step account setup down to 4 without losing compliance checks.",
    description:
      "Northbound's original onboarding flow buried a routine KYC form inside 12 sequential screens. I restructured the flow into four grouped stages without cutting any required compliance content, and validated the new structure with moderated usability testing before development.",
    coverImage: { kind: "placeholder", category: "ui-screen", alt: "Northbound mobile onboarding flow — cover image placeholder" },
    thumbnail: { kind: "placeholder", category: "ui-screen", alt: "Northbound mobile onboarding flow — thumbnail placeholder" },
    gallery: [
      { kind: "placeholder", category: "ui-screen", alt: "Northbound onboarding, full flow overview — gallery placeholder", layout: "full" },
      { kind: "placeholder", category: "ui-screen", alt: "Northbound KYC step, before — gallery placeholder", layout: "half" },
      { kind: "placeholder", category: "ui-screen", alt: "Northbound KYC step, after — gallery placeholder", layout: "half" },
    ],
    featured: true,
    featuredOrder: 1,
    published: true,
    tags: ["Fintech", "Onboarding", "Mobile"],
    tools: ["Figma", "Notion"],
    services: ["Product & UI/UX Design"],
    order: 1,
    caseStudy: {
      overview: "New users abandoned account setup before reaching their first transaction — the fix wasn't shorter copy, it was better grouping.",
      problem: "New users abandoned account setup before reaching their first transaction.",
      context: "Northbound is an early-stage fintech app; account setup includes a regulatory KYC step no user can skip.",
      constraint: "Regulatory copy couldn't be cut, only re-sequenced — legal review added a 2-week bottleneck per iteration.",
      goals: ["Reduce setup abandonment", "Keep every required compliance field", "Ship within the existing legal review cycle"],
      research: "Session recordings showed most drop-off happened at a single dense KYC form, not spread evenly across the flow.",
      researchMethods: ["Session recordings", "Funnel analysis"],
      insights: "Users weren't confused by any one field — they were reacting to the form's length as a single, undifferentiated wall.",
      informationArchitecture: "Reduced the flow from 12 linear screens to 4 grouped stages, each resumable.",
      wireframes: [
        { kind: "placeholder", category: "ui-screen", alt: "Northbound early wireframe, stage grouping — placeholder", layout: "third" },
        { kind: "placeholder", category: "ui-screen", alt: "Northbound early wireframe, progress indicator — placeholder", layout: "third" },
        { kind: "placeholder", category: "ui-screen", alt: "Northbound early wireframe, resumable state — placeholder", layout: "third" },
      ],
      designDirection: "Split the KYC form into progressive steps grouped by why the information was needed, not by data type.",
      finalDesign: [
        { kind: "placeholder", category: "ui-screen", alt: "Northbound final onboarding screen, stage 1 — placeholder", layout: "half" },
        { kind: "placeholder", category: "ui-screen", alt: "Northbound final onboarding screen, stage 2 — placeholder", layout: "half" },
      ],
      testing: "Moderated usability testing with 6 target users validated the regrouping before development.",
      outcome: "Setup completion improved and support tickets referencing the KYC step dropped after launch.",
      reflection: "The regrouping mattered more than any visual polish — worth remembering before reaching for a redesign.",
    },
  },
  {
    id: "fielded",
    title: "Fielded",
    slug: "fielded",
    category: "Branding",
    projectType: "Brand Identity",
    year: 2024,
    client: "Fielded (outdoor gear)",
    role: "Brand Designer",
    shortDescription: "A trail-gear identity built around one adaptable mark instead of a rigid lockup.",
    description:
      "Fielded needed a mark that could survive being reproduced by hand — embroidery, single-color stamping, small-scale print — with no art direction spent on it each time it shipped.",
    coverImage: { kind: "placeholder", category: "brand-mark", alt: "Fielded brand mark and palette — cover image placeholder" },
    thumbnail: { kind: "placeholder", category: "brand-mark", alt: "Fielded brand mark and palette — thumbnail placeholder" },
    gallery: [],
    featured: true,
    featuredOrder: 2,
    published: true,
    tags: ["Identity", "Outdoor", "Logo"],
    tools: ["Illustrator", "InDesign"],
    services: ["Brand Identity & Systems"],
    order: 2,
    caseStudy: {
      overview: "The founder's DIY logo didn't survive embroidery or single-color stamping — the fix had to start from the worst reproduction method, not the best.",
      problem: "The founder's existing DIY logo didn't survive embroidery or single-color stamping.",
      context: "Fielded is a single-founder outdoor gear brand.",
      constraint: "Single-founder budget — no room for a full print system, so the mark had to work unsupervised across print, embroidery, and social with no art direction each time.",
      goals: ["A mark that survives embroidery and single-color stamping", "No ongoing art direction required per use"],
      research: "Audited 20 competitor marks; the strongest ones held up at 10mm and in one flat color.",
      researchMethods: ["Competitive audit"],
      insights: "A literal mountain/compass mark was the expected default — differentiation had to come from restraint, not more detail.",
      designDirection: "Reduce the mark to a single continuous line that still reads at stamp-size.",
      concept: "One mark, one line weight, built to survive the worst reproduction method first.",
      logo: [
        { kind: "placeholder", category: "brand-mark", alt: "Fielded logo, final continuous-line mark — placeholder", layout: "half" },
        { kind: "placeholder", category: "brand-mark", alt: "Fielded logo, single-color stamp version — placeholder", layout: "half" },
      ],
      typography: "One display face for the wordmark, set wide enough to still read at 10mm print — no secondary face, since every use case (embroidery, stamping) already fights for legibility at small sizes.",
      colorSystem: "A two-color system (deep green, bone) chosen for embroidery-thread availability, not aesthetics alone.",
      moodboard: [],
      applications: [
        { kind: "placeholder", category: "brand-mark", alt: "Fielded mark embroidered on a jacket sleeve — placeholder", layout: "third" },
        { kind: "placeholder", category: "brand-mark", alt: "Fielded mark stamped on a hang tag — placeholder", layout: "third" },
        { kind: "placeholder", category: "brand-mark", alt: "Fielded mark on a social profile — placeholder", layout: "third" },
      ],
      outcome: "Shipped a one-page brand sheet the founder now hands directly to print and embroidery vendors with no revisions needed.",
      reflection: "Designing for the worst-case reproduction method first, rather than the best, made every other use case easier.",
    },
  },
  {
    id: "kiln-and-co",
    title: "Kiln & Co.",
    slug: "kiln-and-co",
    category: "Graphic Design",
    projectType: "Editorial / Print System",
    year: 2024,
    client: "Kiln & Co. (restaurant)",
    role: "Graphic Designer",
    shortDescription: "A modular print system so a seasonal menu update never needs a designer again.",
    description:
      "Kiln & Co.'s menu changes seasonally. I built a grid flexible enough to hold together with significantly more or less copy than the launch version, so future updates don't require a new layout job.",
    coverImage: { kind: "placeholder", category: "editorial", alt: "Kiln & Co. menu and print system — cover image placeholder" },
    thumbnail: { kind: "placeholder", category: "editorial", alt: "Kiln & Co. menu and print system — thumbnail placeholder" },
    gallery: [],
    featured: true,
    featuredOrder: 3,
    published: true,
    tags: ["Editorial", "Print", "Menu System"],
    tools: ["InDesign", "Illustrator"],
    services: ["Brand Identity & Systems"],
    order: 3,
    caseStudy: {
      overview: "Every menu revision previously meant a new freelance layout job — the fix was a system, not a one-off design.",
      problem: "Every menu revision previously meant a new freelance layout job.",
      context: "A restaurant client updating prices and dish names seasonally.",
      constraint: "Menu changes seasonally; the owner needed to update prices and dish names in Google Docs without breaking the layout.",
      goals: ["A layout that survives unpredictable copy length", "No designer needed for routine updates"],
      research: "Reviewed 8 past menu PDFs — copy length varied by up to 3x between seasons.",
      insights: "The system needed to survive unpredictable copy length, not just look good with today's copy.",
      concept: "Treat the menu as a template with rules, not a document with content — the grid should survive being rewritten entirely.",
      designDirection: "Build a strict grid with flexible-height sections instead of fixed text boxes.",
      exploration: [
        { kind: "placeholder", category: "editorial", alt: "Kiln & Co. early layout, fixed text boxes — rejected direction, placeholder", layout: "half" },
        { kind: "placeholder", category: "editorial", alt: "Kiln & Co. early layout, flexible grid — placeholder", layout: "half" },
      ],
      designSystem: "One display face for section headers, one workhorse face for dish copy — matching the site's own two-face rule.",
      finalDesign: [
        { kind: "placeholder", category: "editorial", alt: "Kiln & Co. final menu spread, front — placeholder", layout: "half" },
        { kind: "placeholder", category: "editorial", alt: "Kiln & Co. final menu spread, back — placeholder", layout: "half" },
      ],
      applications: [
        { kind: "placeholder", category: "editorial", alt: "Kiln & Co. printed menu on a table setting — placeholder", layout: "full" },
      ],
      outcome: "The owner has since updated the menu twice for seasonal changes without hiring a designer.",
      reflection: "A template built for the worst-case copy length outlasts one designed only for the launch content.",
    },
  },
  {
    id: "ledger",
    title: "Ledger",
    slug: "ledger",
    category: "UI/UX",
    projectType: "Dashboard",
    year: 2023,
    client: "Ledger (B2B SaaS)",
    role: "UX Researcher & Designer",
    shortDescription: "Redesigned a finance dashboard around the 3 questions users actually opened it to answer.",
    description:
      "Ledger's dashboard had grown to 40+ metrics over time. Rather than cutting any of them, I re-ranked the layout around the handful of goals that accounted for most daily visits.",
    coverImage: { kind: "placeholder", category: "ui-screen", alt: "Ledger dashboard interface — cover image placeholder" },
    thumbnail: { kind: "placeholder", category: "ui-screen", alt: "Ledger dashboard interface — thumbnail placeholder" },
    gallery: [],
    featured: true,
    featuredOrder: 4,
    published: true,
    tags: ["B2B", "Dashboard", "Data"],
    tools: ["Figma", "Notion"],
    services: ["Product & UI/UX Design", "UX Research & Strategy"],
    order: 4,
    caseStudy: {
      overview: "Users opened the dashboard daily but consistently used only a handful of its metrics — the fix was re-ranking, not redesigning.",
      problem: "Users opened the dashboard daily but consistently used only a handful of its metrics.",
      context: "A B2B SaaS finance dashboard with an entrenched, stakeholder-approved metric set.",
      constraint: "The existing dashboard had 40+ metrics already shipped — nothing could be deleted outright without stakeholder sign-off per metric.",
      goals: ["Surface the metrics users actually check daily", "Change nothing that requires per-metric stakeholder approval"],
      research: "Interviewed 9 users and tagged every dashboard visit's stated goal against the metric they actually looked at first.",
      researchMethods: ["User interviews", "Usage tagging"],
      insights: "Three recurring goals accounted for most visits; the rest of the dashboard was reference material, not a daily read.",
      designDirection: "Promote the 3 goal-aligned views to a fixed summary row, move the rest behind a secondary tab — nothing deleted, everything re-ranked.",
      testing: "A/B tested the summary row against the original layout with a subset of accounts before full rollout.",
      outcome: "Daily active usage of the dashboard increased and support requests asking \"where do I find X\" dropped.",
      reflection: "Re-ranking existing information beat redesigning it — most of the value was already there, just buried.",
    },
  },
  {
    id: "verge-studio",
    title: "Verge Studio",
    slug: "verge-studio",
    category: "Branding",
    projectType: "Brand Identity",
    year: 2023,
    client: "Verge Studio",
    role: "Brand Designer",
    shortDescription: "A flexible identity system for a two-person studio pitching against agencies 10x their size.",
    coverImage: { kind: "placeholder", category: "brand-mark", alt: "Verge Studio brand identity — cover image placeholder" },
    gallery: [],
    featured: false,
    published: true,
    tags: ["Identity", "Creative Studio"],
    tools: ["Illustrator", "Figma"],
    services: ["Brand Identity & Systems"],
    order: 5,
    caseStudy: {
      overview: "The studio's existing identity read as smaller and less capable than the agencies it competed against — confidence had to come from restraint, not scale.",
      problem: "The studio's existing identity read as smaller and less capable than the agencies it competed against.",
      constraint: "No dedicated marketing budget — the identity had to work as a pitch-deck cover with zero additional design time.",
      research: "Compared pitch decks from 5 competing agencies to find what visual signals implied scale and confidence.",
      insights: "Confidence read through restraint and type, not through visual density or client-logo walls.",
      designDirection: "Lead every touchpoint with oversized type and negative space instead of imagery.",
      concept: "One confident type treatment as the studio's signature, reused everywhere from deck covers to email signatures.",
      logo: [],
      outcome: "The studio reports the new deck cover is the single most-commented-on slide in new pitches.",
    },
  },
  {
    id: "almanac",
    title: "Almanac",
    slug: "almanac",
    category: "Graphic Design",
    projectType: "Poster Series",
    year: 2023,
    client: "Almanac Lecture Series",
    role: "Graphic Designer",
    shortDescription: "A poster series for a lecture series, designed to work as a set even when displayed one at a time.",
    coverImage: { kind: "placeholder", category: "poster", alt: "Almanac campaign poster series — cover image placeholder" },
    gallery: [],
    featured: false,
    published: true,
    tags: ["Campaign", "Poster", "Typography"],
    tools: ["Illustrator", "InDesign"],
    services: ["Brand Identity & Systems"],
    order: 6,
    caseStudy: {
      overview: "The prior year's posters looked identical to generic stock event flyers — the fix was a shared system, not a shared image.",
      problem: "The prior year's posters looked identical to generic stock event flyers.",
      constraint: "Posters were printed and hung individually across a campus, rarely seen side by side — each one had to read as part of a series alone.",
      research: "Walked the actual display locations to see how posters were typically viewed — in passing, at a distance, one at a time.",
      insights: "A shared system (not a shared image) was what would make a lone poster still read as part of a series.",
      designDirection: "Fix type and grid rules across every poster, let the numeral for each lecture be the only variable.",
      applications: [],
      outcome: "Series was extended for a second semester at the department's request.",
    },
  },
  {
    id: "pathway",
    title: "Pathway",
    slug: "pathway",
    category: "UI/UX",
    projectType: "Mobile App",
    year: 2022,
    client: "Pathway",
    role: "Product Designer",
    shortDescription: "A habit-tracking app redesigned around missed days, not just streaks.",
    coverImage: { kind: "placeholder", category: "ui-screen", alt: "Pathway wellness app interface — cover image placeholder" },
    gallery: [],
    featured: false,
    published: true,
    tags: ["Wellness", "Mobile", "iOS"],
    tools: ["Figma"],
    services: ["Product & UI/UX Design"],
    order: 7,
    caseStudy: {
      overview: "Users who missed a single day tended to delete the app rather than resume their streak — the fix was reframing failure, not adding features.",
      problem: "Users who missed a single day tended to delete the app rather than resume their streak.",
      constraint: "Small team, no dedicated research budget — research had to run alongside design, not before it.",
      research: "Ran a lightweight diary study with 5 lapsed users to understand what happened right after a missed day.",
      researchMethods: ["Diary study"],
      insights: "The all-or-nothing streak counter made a single miss feel like total failure, not a normal part of the habit.",
      designDirection: "Replace the streak counter with a rolling consistency view that a missed day doesn't zero out.",
      testing: "Prototype testing showed the rolling view reduced stated intent to delete the app after a miss.",
      outcome: "Post-launch, 30-day retention among users who missed at least one day improved over the streak-only version.",
    },
  },
  {
    id: "salt-and-ash",
    title: "Salt & Ash",
    slug: "salt-and-ash",
    category: "Graphic Design",
    projectType: "Packaging",
    year: 2022,
    client: "Salt & Ash",
    role: "Graphic Designer",
    shortDescription: "A shelf-ready packaging system for a 6-SKU spice line, built from one template.",
    coverImage: { kind: "placeholder", category: "packaging", alt: "Salt & Ash packaging system — cover image placeholder" },
    gallery: [],
    featured: false,
    published: true,
    tags: ["Packaging", "CPG"],
    tools: ["Illustrator", "Photoshop"],
    services: ["Brand Identity & Systems"],
    order: 8,
    caseStudy: {
      overview: "Early concepts required a unique layout per SKU, which the print budget couldn't support — the fix was one template with one variable.",
      problem: "Early concepts required a unique layout per SKU, which the print budget couldn't support.",
      constraint: "Six SKUs needed to ship together on a fixed print-run budget, ruling out a fully custom label per flavor.",
      research: "Reviewed the shelf context at 2 target retailers to see how the line would actually compete for attention.",
      insights: "Consistent silhouette across all 6 SKUs read as more premium on-shelf than variety did.",
      designDirection: "One label template, one variable: a single accent color and icon per flavor.",
      applications: [],
      outcome: "Delivered all 6 SKUs within the original print budget with no per-SKU design revisions needed.",
    },
  },
];
